## YOU PROBABLY WANT TO ADJUST THIS CONFIGURATION TO USE GITOPS REPOS YOU OWN
## AND CAN PUSH TO!!!
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akuityio/k8sta-guestbook-deploy
    targetRevision: env/dev
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akuityio/k8sta-guestbook-deploy
    targetRevision: env/stage
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akuityio/k8sta-guestbook-deploy
    targetRevision: env/prod
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
