apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: repo-1777030974
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
stringData:
  type: git
  project: default
  url: https://github.com/akuityio/k8sta-guestbook-deploy
  username: # Use your own GitHub handle here
  password: # Use your own personal access token here
