apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-k8sta-dev-cluster
product: kind
registry: k8sta-dev-registry
kindV1Alpha4Cluster:
  nodes:
  - extraPortMappings:
    - containerPort: 30080
      hostPort: 30080
    - containerPort: 30081
      hostPort: 30081
    - containerPort: 30082
      hostPort: 30082
    - containerPort: 30443
      hostPort: 30443
