name: CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  DEV_IMAGE_NAME: ghcr.io/akuityio/k8sta-tools:v0.2.0
  IMAGE_NAME: krancour/k8sta

jobs:

  test-unit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/akuityio/k8sta-tools:v0.2.0
      credentials:
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
      env:
        SKIP_DOCKER: 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: /go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Run unit tests
      run: make test-unit

  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/akuityio/k8sta-tools:v0.2.0
      credentials:
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
      env:
        SKIP_DOCKER: 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: /go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Run linter
      run: make lint

  lint-chart:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/akuityio/k8sta-tools:v0.2.0
      credentials:
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
      env:
        SKIP_DOCKER: 'true'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run linter
      run: make lint-chart

  build:
    needs: [test-unit, lint, lint-chart]
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Multiarch build
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64,linux/arm64
        push: false

  scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Single arch build
      id: build
      uses: docker/build-push-action@v3
      with:
        push: false
        load: true
    - name: Scan image
      uses: anchore/scan-action@v3
      with:
        image: ${{ steps.build.outputs.imageid }}
        output-format: table
      continue-on-error: true
